import { Metadata } from 'next';
import Contract from '../components/Contract';
import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className={styles.main}>
      <div>
        <p>Welcome to the Truffle + Next + Recoil box.</p><br />
        <p>To begin:</p> <br />
        <ul>
          <li>Replace the smart contract in the <code>truffle</code> directory with yours</li>
          <li>Open <code>truffle/migrations</code> and add a new migration file similar to the one there already for the test smart contract. </li>
          <li><code>cd</code> into the <code>truffle/</code> directory and run <code>truffle migrate</code> to deploy your new smart contract</li>
          <li>Open up <code>EthProvider.tsx</code> and modify the smart contract JSON import line to correctly point to your own deployed smart contract JSON.</li>
          <li>To access the global <code>eth</code> state, simply do:<br /><br /><code>const [eth] = useRecoilState(ethState)</code><br /></li>
        </ul> <br />

        <p>Check <code>Contracts.tsx</code> to see how it is being used there. This <code>eth</code> object contains three properties:</p>
        <ul>
          <li><code>contractMethods</code>: This is an object containing all the public methods available on the smart contract</li>
          <li><code>contractAddress</code>: The smart contract address</li>
          <li><code>address</code>: The address of the connected MetaMask account</li>
        </ul>

        <br />

        <Contract />

      </div>
    </main>
  )
}
